language: php

php:
  - 7
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly

install:
  - travis_retry composer update --no-progress --prefer-dist --profile

before_script: 
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/
  - grunt build
  - cd $TRAVIS_BUILD_DIR/extensions/VisualEditor/lib/ve/
  - grunt build

script:
  - composer test
